spring:
  application:
    name: user-service
jwt:
  secret: ${JWT_SECRET} #set Docker Run Option "--env-file ./.env.example"
#  datasource:
#    url: jdbc:mysql://localhost:3307/user_db?createDatabaseIfNotExist=true
#    username: root
#    password: MyP@ssword!
#  jpa:
#    show-sql: true
server:
  port: 4003
