spring:
  application:
    name: user-service
jwt:
  secret: Ub0xySfmMwUWcA7Hp1uKL0TNuH7L4gX6/yCBvtUXCDZw5XXa9AbNkG56GrGp3MfKaJkLHDmXOArJh/mESsvqcg==
#  datasource:
#    url: jdbc:mysql://localhost:3307/user_db?createDatabaseIfNotExist=true
#    username: root
#    password: MyP@ssword!
#  jpa:
#    show-sql: true
server:
  port: 4003
