spring:
  application:
    name: garage-service
  datasource:
    url: jdbc:mysql://localhost:3306/garage?createDatabaseIfNotExist=true
    username: root
    password: MyP@ssword!
  jpa:
    show-sql: true